# Generated by Django 2.2.12 on 2020-05-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='clase',
            field=models.CharField(default='', max_length=200),
        ),
    ]
